### ISSUE TITLE
Finding new can IDs 

### ISSUE THREAD

**Issue by zorrobyte** [gregjhogan/openioc#3]
I just found AutoPi, it would be awesome if Cabana had something like this:
https://www.autopi.io/blog/discover-hidden-functions-in-your-car-with-can-bus/

![image](https://user-images.githubusercontent.com/7257172/120897720-99a02200-c5f5-11eb-934d-67f7c5794a73.png)

Could also be used to find new signals for this project

**Comment by gregjhogan** [comment]
Signals in this project aren't really like that.  They currently all use UDS/KWP2000 which is a request/response protocol.  They don't happen during normal operation of a vehicle.  Everything in here so far was found by opening up the diagnostic tools for the vehicle, recording a test, and analyzing the communication for an already known time window.  Then for undocumented things, scanning addresses using similar patterns one at a time while sitting in your car and watching what happens.
